service: alegra-pets-training-fundations-backend
frameworkVersion: '3'

useDotenv: true

custom:
  common: ${file(../serverless.common.yml)}
  esbuild:
    target: 'node14'
    exclude: [
      'aws-sdk', 
      'jsonwebtoken', 
      'aws-lambda',
      'ulid',
    ]

plugins: ${self:custom.common.plugins}

provider: ${self:custom.common.provider}

functions:
  createFundation:
    name: create-fundation-${opt:stage}
    handler: src/create-fundation.handler
    layers:
      - 'Fn::ImportValue': ${env:JWT_LAYER_ARN}
      - 'Fn::ImportValue': ${env:ULID_LAYER_ARN}
      - !Ref S3LoggerLambdaLayer
    environment:
      FUNDATIONS_TABLE_NAME:
        'Fn::ImportValue': ${env:FUNDATIONS_TABLE_NAME}
      JWT_SECRET: ${env:JWT_SECRET}
    events:
      - httpApi:
          path: /fundations
          method: post
 
layers:
  s3Logger: 
    path: ../layers/shared
    name: s3-logger-${opt:stage}
    compatibleRuntimes:
      - nodejs14.x
      - nodejs16.x


